services:
  rstudio:
    build: ./rstudio
    container_name: m4a-rstudio
    ports:
      - "3939:8787"
    environment:
      PASSWORD: rstudio
    volumes:
      - ./shiny/app:/home/rstudio/project/shiny
    restart: unless-stopped
